# Generated by Django 3.1.5 on 2021-01-27 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.date(2021, 1, 27), verbose_name='Дата'),
        ),
    ]
